# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0e547f65dab5d2bb028403b23580a857d44c02b3fe21dabcdd2b4b29ad4f535127ce0f357fe2d66ebb350133e7b1d0991fd12ac7f78c708cc171f630aadf39e

test:
  secret_key_base: 35108eab50a959fc72f37caf8e6dd6f37585f69f90c89d8d05d71759fd33b80ffb1965cd4ae1eb77f2dff9e69594a25a3c58173d3cbe96e6352bc3cfd611be65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
